include: 
  - ${TOM_DESC_DIR:-../tom_desc}/tests/docker-compose.yaml
services:
  resspect:
    tty: true
    container_name: resspect
    build: ./
    volumes:
      - type: bind
        source: ./
        target: /resspect/resspect-src
      - type: bind
        source: ./example_work_dir
        target: /resspect/resspect-work
      - type: bind
        source: ./secrets
        target: /secrets
        bind:
          create_host_path: true
    environment:
      - DB_USER=admin
      - DB_PASS=verysecurepassword
      - DB_HOST=resspectdb
      - DB_PORT=5432
      - DB_NAME=resspectdb
      - TOM_USERNAME=root
      - TOM_PASSWORDFILE=/resspect/passwordfile.txt
      - TOM_URL=http://tom:8080
