services:
  resspect:
    tty: true
    container_name: resspect
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - "db"
    volumes:
      - type: bind
        source: ./
        target: /resspect/resspect-src
      - type: bind
        source: ./secrets
        target: /secrets
        bind:
          create_host_path: true
    environment:
      - DB_USER=admin
      - DB_PASS=verysecurepassword
      - DB_HOST=resspectdb
      - DB_PORT=5432
      - DB_NAME=resspectdb
    networks:
      - tom_desc_default
  db:
    container_name: resspectdb
    image: postgres
    networks: 
      - tom_desc_default
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=verysecurepassword
      - POSTGRES_DB=resspectdb
      - POSTGRES_DATA_DIR=/docker-entrypoint-initdb.d
    volumes:
      - type: bind
        source: ./resspectdb.sql
        target: /docker-entrypoint-initdb.d/resspectdb.sql
      - type: bind
        source: ./src/resspect
        target: /resspect
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d resspectdb"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  tom_desc_default:
    external: true

