name: Run end-to-end tests

on:
  pull_request:
  push:
  workflow_dispatch:
#  schedule:
#    # Run every Sunday at 04:53 UTC
#    - cron: 53 4 * * 0

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install package inside virtual environment
        run: |
          python3.9 -m venv venv
          source venv/bin/activate
          python -m pip install -U pip setuptools
          python -m pip install .

      - name: Run pipeline for SNPCC
        run: |
          source venv/bin/activate
          ./tests/resspect/run-snpcc-e2e.sh
